name: Youth

on:
  workflow_dispatch:
  schedule:
     - cron: '11 8 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        YOUTH_HEADER: ${{ secrets.YOUTH_HEADER }}
        YOUTH_ARTBODY: ${{ secrets.YOUTH_ARTBODY }}
        YOUTH_REDBODY: ${{ secrets.YOUTH_REDBODY }}
        YOUTH_TIME: ${{ secrets.YOUTH_TIME }}


    steps:
      - name: Checkout
        run: |
          git clone https://github.com/WWS321/Y5QGMErwnXmGyH.git ~/bbb
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.YOUTH_HEADER
        run: |
          cd ~/bbb
          npm install
      - name: '运行 【Youth】'
        if: env.YOUTH_HEADER
        run: |
          cd ~/bbb
          node youth.js
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}